config/routes.rb
Rails.application.routes.draw do
  resources :researches, path: "research"

  resources :aspects

  root 'researches#index'

end

app/models/aspect.rb
class Aspect < ActiveRecord::Base
    validates :aspect, presence: true
    validates :keywords, presence: true
    validates :component1, presence: true
end

app/models/research.rb
class Research < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/aspects_controller.rb
class AspectsController < ApplicationController
  before_action :set_aspect, only: [:show, :edit, :update, :destroy]

  # GET /aspects
  # GET /aspects.json
  def index
    @aspects = Aspect.all.order(:aspect)
  end

  # GET /aspects/1
  # GET /aspects/1.json
  def show
  end

  # GET /aspects/new
  def new
    @aspect = Aspect.new
  end

  # GET /aspects/1/edit
  def edit
  end

  # POST /aspects
  # POST /aspects.json
  def create
    @aspect = Aspect.new(aspect_params)

    respond_to do |format|
      if @aspect.save
        format.html { redirect_to aspects_url, notice: 'Aspect was successfully created.' }
        format.json { render :show, status: :created, location: @aspect }
      else
        format.html { render :new }
        format.json { render json: @aspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aspects/1
  # PATCH/PUT /aspects/1.json
  def update
    respond_to do |format|
      if @aspect.update(aspect_params)
        format.html { redirect_to @aspect, notice: 'Aspect was successfully updated.' }
        format.json { render :show, status: :created, location: @aspect }
      else
        format.html { render :edit }
        format.json { render json: @aspect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aspects/1
  # DELETE /aspects/1.json
  def destroy
    @aspect.destroy
    respond_to do |format|
      format.html { redirect_to aspects_url, notice: 'Aspect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aspect
      @aspect = Aspect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aspect_params
      params.require(:aspect).permit(:aspect, :keywords, :component1, :component2, :sources)
    end
end

app/controllers/researches_controller.rb
class ResearchesController < ApplicationController

  # GET /researches
  # GET /researches.json
  def index
  end

  def create
    @neo = Neography::Rest.new
    node_check = @neo.execute_query("START a = node(*) RETURN ID(a), a.name;")["data"].collect{|n| {"id" => n[0], "name" => n[1]} }
    if node_check.empty?
      create_person
      add_aspect_map
    end
    #mapid = @neo.execute_query("START n = node(*) MATCH (n) WHERE n.name = 'Tenebrae' RETURN ID(n);")["data"]
    #map = @neo.get_node(mapid)
    # add_aspect_map
    aspect_from_object = Aspect.find(research_params[:aspect_from])
    aspect_to_object = Aspect.find(research_params[:aspect_to])
    aspect_from = get_node(aspect_from_object.aspect)
    aspect_to = get_node(aspect_to_object.aspect)
    min_distance = (research_params[:min_distance].to_i + 1)
    #route =degrees_of_separation(aspect_from.first, aspect_to.first, research_params[:min_distance].to_i)
    route = []
    degrees_of_separation(aspect_to.first, aspect_from.first, min_distance).each do |path|
      if path["names"].size > min_distance
        route << "Distance: #{(path["names"].size - 2 )} Path: #{path["names"].join(' => ')}"
      end
    end
    respond_to do |format|
      flash[:notice] = route.join("<br />").html_safe
      format.html { redirect_to root_url }
    end
  end
  def create_person
    aspects = Aspect.all
    aspects.each { |aspect|
      @neo.create_node("name" => aspect.aspect)
    }
  end

  def add_aspect_map
    aspects = Aspect.all
    aspects.each { |aspect|
      if !aspect.component2.empty?
        aspect_aspect = get_node(aspect.aspect)
        aspect_component1 = get_node(aspect.component1)
        aspect_component2 = get_node(aspect.component2)
        @neo.create_relationship("aspect", @neo.get_node(aspect_aspect.first), @neo.get_node(aspect_component1.first))
        @neo.create_relationship("aspect", @neo.get_node(aspect_component1.first), @neo.get_node(aspect_aspect.first))
        @neo.create_relationship("aspect", @neo.get_node(aspect_aspect.first), @neo.get_node(aspect_component2.first))
        @neo.create_relationship("aspect", @neo.get_node(aspect_component2.first), @neo.get_node(aspect_aspect.first))
      end
    }
  end

  def get_node(aspect)
    @neo.execute_query("START n = node(*) MATCH (n) WHERE n.name = '#{aspect}' RETURN ID(n);")["data"]
  end

  def degrees_of_separation(start_node, destination_node, depth)
    # paths =  @neo.get_paths(start_node,
    #                         destination_node,
    #                         {"type"=> "aspect", "direction" => "in"},
    #                         depth=7,
    #                         algorithm="allPaths")
    paths = @neo.get_paths(start_node,
      destination_node,
      {"type"=> "aspect", "direction" => "in"},
      depth=depth,
      algorithm="allPaths"
    )
    #paths = @neo.get_paths(start_node, destination_node, {"type" => "aspect"})
    #paths = @neo.get_node_relationships(start_node)
    paths.each do |p|
    p["names"] = p["nodes"].collect { |node|
       @neo.get_node_properties(node, "name")["name"] }
    end
  end
  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def research_params
      params.require(:index).permit(:aspect_from, :aspect_to, :min_distance)
    end
  # def create
  #   @aspect_from = Aspect.find(research_params[:aspect_from])
  #   @aspect_to = Aspect.find(research_params[:aspect_to])
  #   @min_distance = research_params[:min_distance].to_i
  #   @current_step = 1
  #   @steps = []
  #   @alternate_route = []
  #   respond_to do |format|
  #     format.html { redirect_to root_url, notice: "From: #{@aspect_from.inspect}, To: #{@aspect_to.inspect}, Min Distance: #{@min_distance}, Current Step: #{@current_step}, Possible steps: #{compare_step_chance}" }
  #   end
  # end
  # private
  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def research_params
  #     params.require(:index).permit(:aspect_from, :aspect_to, :min_distance)
  #   end
    
  #   def is_primal(aspect)
  #     aspect.component1 == "Primal" ? true : false
  #   end
    
  #   def possible_steps(aspect)
  #     Aspect.select(:id, :aspect).where("component1 = ? or component2 = ?", aspect.aspect, aspect.aspect)
  #   end
    
  #   def compare_step_chance
  #     possible_steps_local = []
  #     aspect_from = @current_step == 1 ? possible_steps(@aspect_from) : @steps[@current_step - 2]
  #     aspect_to = possible_steps(@aspect_to)
  #     steps = aspect_from & aspect_to
  #     if @current_step <= @min_distance && steps.any?
  #       steps.each { |step|
  #         possible_steps_local << step.aspect
  #       }
  #       @current_step += 1
  #       @steps.push(possible_steps_local)
  #       compare_step_chance
  #     elsif @current_step <= @min_distance
  #       # @steps.push(aspect_from)
  #       @steps.push(["from"])
  #       @current_step += 1
  #       compare_step_chance
  #     else
  #       @steps
  #     end
  #   end
    
  #   def find_alternate_route(aspect_from, aspect_to)
      
  #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aspects_helper.rb
module AspectsHelper
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/views/aspects/_form.html.erb
<%= form_for(@aspect) do |f| %>
  <% if @aspect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aspect.errors.count, "error") %> prohibited this aspect from being saved:</h2>

      <ul>
      <% @aspect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><%= f.label :aspect, "Aspect Name: " %></td>
      <td><%= f.text_field :aspect %></td>
    </tr>
    <tr>
      <td><%= f.label :keywords, "Keywords: " %></td>
      <td><%= f.text_field :keywords %></td>
    </tr>
    <tr>
      <td><%= f.label :component1, "Component 1: " %></td>
      <td><%= f.text_field :component1 %></td>
    </tr>
    <tr>
      <td><%= f.label :component2, "Component 2: " %></td>
      <td><%= f.text_field :component2 %></td>
    </tr>
    <tr>
      <td><%= f.label :sources, "Sources: " %></td>
      <td><%= f.text_field :sources %></td>
    </tr>
  </table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aspects/edit.html.erb
<h1>Editing aspect</h1>

<%= render 'form' %>

<%= link_to 'Show', @aspect %> |
<%= link_to 'Back', aspects_path %>

app/views/aspects/index.html.erb
<h1>Listing aspects</h1>
<%= link_to 'New Aspect', new_aspect_path %>
<br />
<table>
  <thead>
    <tr>
      <th align="left">Aspect Name</th>
      <th colspan="3" align="left">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @aspects.each do |aspect| %>
      <tr>
        <td><%= aspect.aspect %></td>
        <td><%= link_to 'Show', aspect %></td>
        <td><%= link_to 'Edit', edit_aspect_path(aspect) %></td>
        <td><%= link_to 'Destroy', aspect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/aspects/new.html.erb
<h1>New aspect</h1>

<%= render 'form' %>

<%= link_to 'Back', aspects_path %>

app/views/aspects/show.html.erb
<p id="notice"><%= notice %></p>
<table>
    <tr>
        <td>Aspect Name:</td>
        <td><%= @aspect.aspect %></td>
    </tr>
    <tr>
        <td>Keywords:</td>
        <td><%= @aspect.keywords %></td>
    </tr>
    <tr>
        <td>Component 1:</td>
        <td><%= @aspect.component1 %></td>
    </tr>
    <tr>
        <td>Component 2:</td>
        <td><%= @aspect.component2 %></td>
    </tr>
    <tr>
        <td>Sources:</td>
        <td><%= @aspect.sources %></td>
    </tr>
</table>
<%= link_to 'Edit', edit_aspect_path(@aspect) %> |
<%= link_to 'Back', aspects_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/researches/index.html.erb
<h1>Research</h1>
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Starting Aspect</th>
      <th>Ending Aspect</th>
      <th>Minimum Distance</th>
    </tr>
  </thead>

  <tbody>

  <%= form_for(:index) do |f| %>
  <tr>
    <td><%= f.select :aspect_from, Aspect.all.collect { |a| [a.aspect, a.id] } %></td>
    <td><%= f.select :aspect_to, Aspect.all.collect { |a| [a.aspect, a.id] } %></td>
    <td><%= f.select :min_distance, (1...11).step(1).to_a.map { |i| [i, i] } %></td>
  </tr>
  <tr colspan="2">
    <td><%= f.submit "Search" %></td>
  </tr>
  <% end %>
  </tbody>
</table>